# Generated by Django 5.1.4 on 2025-06-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='destination',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
